---
apiVersion: v1
kind: Secret
metadata:
  name: "temporal-wieisdetrol-key"
data:
  client.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBdTNEYVN6VVlaRE1TY01nOXNIQnBHNlhQc0xaWllYSEQ3ZVk1UmhIZ2xRWkpuSTdjCk8yeVA4KzlScmgrcHRDU0xEQzhqSyt5dWI0VFBFcGtpL3lvdVR1UzJGc1Q2QmRobHVVaFB2YTFZV1dtQ21ncEYKOHROUzlOajUrSkZoV1RXQlJGTlVLOEZpbHpIbXhtUnY3Z3U4eU9jTFJTdlNKT2VsTWZVcWg5L1MyUUhVT0w0dwo2L1Ewam5OUXVPRVN2UXRiSFM5TUNzeEZlaEgrK1hUM2FNOXU1UlJoZTArK0pRcWxVSy9icElWc3VLRkUwYTJWClQxek84TVJDU0VHdFZuYWxMRHlrNjZVaWVHYzlyY1dYMC9meGxaK3g1ZHJBVG45cTBoVVUwSEN5c3B6aG1aN3AKbythS3grTll1Y3YvOFBtbVIySXk4TU1sWWprSE5WVklsZHU5bmU0NzNRSTN0MmUrTlFvTVlscFp5dDloYUR0cgpjVW54NXJjRHpyYkZObG83QjVXcEJ1QnNrMWYxaGc1RHdmYmtuM2VIK0ZvMVRMVno0NHJtb25DZk94UUFDSENCCmZJelRNbkRrbC96L2tINVJoZGF3VWpaTnhSQzhTczU1ejVheUc3R1hZbTZuaUUvR3Y2SHl0eVprenFuMkJKT24KTjl1QkxKQk0vUnAzZXJWN0xOWVJ5Vm8wWE50RHo3Y3RCQmZVWHdUTnFuYVV2czZySTRhSUh1emVmQ010SGtmWApTbEpCYjJDTXRuRTNsREpjMnBnanpydEJqWjA1SURDaWNFUU1UVDQvb1BmV2FqWnk4Q0g0TXlaVlVTMDd0MkxRCldleVIzQ01DRm1jMFlGVUJiVzN2UXcyWnZuQllNVEJxMmVEUW43cG1Ca0RtRVFyNmpha0JPNFp6bzJFQ0F3RUEKQVFLQ0FnQUo2RlRBTWNIYURBRmZHNVVpZ01mc0taeHhMcXVmU2w3aVJ5OXRwczlzT1IxR0lmUDk5OGFpZDNBbAp2Vy9nSzlLbUN5TjNYeWJpUEtRZ1lNbE5oay9WSk9MWXV4ZlhIQmJXWkw0dG5GNXdPQjJWTnYxTVc1aXdoS2FECjJjQUtSeTU2YTMxN3VaaXA2Qk5CYkhqUkhaR0xQS1o4YjhKSForOXovNkxtOUlaUWZrMEJlZERHckExa3lTOXkKQjVnN1lnQ3lmeUtYRmRzeDhRWm43azQ1M2ZCZE9mR2tJd3A5MVQxTjV1OFJHQlN2Z1ZDM1ZPUkY3TFhWMnAzVwpucjF0aXZtL1BVTzBzL0ZwbEFBWjNHT2lmK0luRFQ1SjZXdmk5UHBkdVRaZmhTYkxrNTRiY0xUN1VFU0kwbTdKCkZWYkZpSlh6Z3lYYnFET2tremRGdmFpeVNSK1JoTDJLbE9UVWR4MWpqSEZhd0p3d0drckZpeGlsNWxYaVZpK3UKQmtibm5DNnozb0hVU3pnbkZtWmNYaHc1ZzdMN0U0Vys1bFl3K1BkMkZudk83akthdmhhTUtOOUxPZnVORzJZRQoyaGhKckhDaHlZUXEwU2x6MDFRb2pCbjN4a053aVZNbVVqbjJiZTMybTZsSktwU2xscU1wMjIrVzFDa2NRUTdTClpUMHRISGdVbkh6eEJKeVRMUHFRejN0N3FOK2NsS3psUHhpaCtrZVJtSWtuVUViTFZCSUdFWUpXczk4N1hsTVoKeFZiaHRHdTh2SWJ3dGR4YzRmdG1FTmZQSHM0OHlUbnM2UWJ5WXowZUZQczg1WkZzQW9XRkplR1RNZ08wRlN3VApveGNDdHZoVmxSUExjMExWSlJBR1l6L0UzUFo5c0F5K3FoYzJWZ0lCL3hzSStzcHlCUUtDQVFFQTNCWjdONjFwCmRKTUg4bllWdE5ncGZscG9RZVNZNWo4WEc1M0Fab0VPUjBTZWRncDFWYzUwMTF4L09uc0x5MHdJUjlVQ1hJK3IKd3c0NytHMVVScUtaRTBNcHFYdDhhbm5Sbm0vbkdYZ0JrY1NtbC9HTVArWXorNmJyWGlscnZlSWh3VEM2dkg4Two1Q210aU1Mc0krMUExV3VabHZOZkdlUmduN3ZTQi9HSTJ3dTN3N3lyeXZOaU1OSlFuYk9NQ2pzL1hPQXkxaWl3ClJmYS9HN3VkMWhPejlvM083M3dhemVKRnZFcStjNDEyaXBjUnlEVzZzTXI0MWxBV2tocUhiMUhsSUZCaUd2REEKeXhCNU1iZ0EzSkFrbm5ROGF5bTVXMHJ1dVA0VkRxTUxRTDRYWkNSRWF0YUd5WTBpTS91OWd6UVBCZ25IQVBhdAp4ZzZkeXpiVmduOGNGUUtDQVFFQTJnYWowZzloVmFXTFkrVzBROG5xS1MrUEorRWorck5vYmZkM00zZnRNV2U3Ci9wQ1NvbE5POVl6ZVhsWDZGY0l6aEptZjY2dUJjT0pJODY0Ym9qUDlRQ0UzUjdPRFo4b2pnWnJQeUkwcFBtWGYKVTVhMmNZMm9WeWlWZnlyRDF2K1NPVXB4M2pnZUZoKzVyQ3BrZWJPMENuSUJtK1BGUTg1cVVPcVVjZUdjbjBIUwowcE9TNlNxUTNDTHJDT3h1SjZEV1g3OFFKem9UV3p2R3RFbVpjRUQvWnAxcVNzSlM0YmhRR00xZEx6OURnM2Q4Cm5PTmRFRmJQYmRnOWI5djAxTmw1czdLL1VCaFZZdCtQMUdqVGxHRjRLYkZFUTExY1hsZUt0Yko3VHNDbjU4YnIKWkp1d2o2bXZjTnQrTCtuQ2s3ZlMzSkZOL0pvTEhwMktMcVlHMGFQaEhRS0NBUUVBeXRqQm1sQnZHSzJITHBaZApiVCtxQnJYbXo0eVV5K21zTDV6V3Z1TUZ1UFBxcE5zQXlDUXdGbW8vTFRSSmE0ZFpQbk41Nkx2V1VFSG5UaEhlCkVmZzg0NzhNUUJQN1dOdU1NdDNxZnRQWGhuVmNJa0RUeGZVelJpYlRXZ2NOTVlhaEc4RUE2MGlqL2ZEWDYydlUKWDB5RmErN3ZNV3gvNDRwVThBUVpFWTh4VnNwWEJjWDRCR2NMd2ZtbHFhUFpWM2pCN3FVSTFjL01uNzlLNXBHbQphSy9pTjBUK1RFWHpJbjBCVHdrSXZkSE5SdkR6eDdhVnFlcDVMSFhHUjhUQnZQMGJGQXhpVDNoRUNTVFd2dGRiCm0rNFNnaVNacHg5ZW9tRE80NXZ5NW5tcG5uTlZkY3ZqYnlEb1BBMmpUNHdmWURUei85bTFIQk0vbUlMU05vRUUKaW5FQy9RS0NBUUF6RW9zZGtlekRHMXhqc2xOZjdkU2tnVGVQcC9XOXJIa3lDVjRxK0ZUZjFlVDc1UEgwaEg5aQpsZlVoTkJLNU5oekxXeEZUSzRITzU3TWZJaEhuRlRhbDV5SUQ4ZEUrWnVPYVlLRjc0VlZnQUkwb0Q0MzlXNm1yCmdSNUVBOGlNZktITU9kd2lxaEtpTEJ4YWNEUEpMb2RtU3Y2RmZmMmZ2S0s3QWJoMFZOMVRrUi9KcERndDFvTEkKam9Wd09iSTBKa0VSZkxoVCtBN0F1R2Y3bzZJRjRiUHlYYjJnZFpUa3UwQklEeE5kRmZ6Q3R5TEJ2YUQzU3Q2YwpaS00vcU03WmJYaE0xL3BvME1wdnR0OENhdXZsUGsvZnRGN0JTUVZ5TkIrU0lKVXlCWDlQbEJGZ0ovaGNMdXVpCkRFaXJBSjlMNnl2QjcyZk5YR2h1YTRrTEZHbFVnb2NoQW9JQkFIelVteFI5MlNJeW9CbFR1Qk9RV2gydWxXOE4KaEVwRTE2MzZXK2p0MmVHT1BYc2JRTEg2UFpJNVZUZHgxUHBWUnJVRSt1M0JNMW81dCtyWXU0THBKcUZ5ZGM3Vgp5ZmtBVHFPRG1uV2Ewa0ZNa1pGVjNoMS8ycDUrRG1UNG96eWpjbCtlR2V3SUhTeGw1eFVickZodlZLWk1JbzRrCkFCQzIvclVreDFkYU90TFUwWmlFTTNySkR2NHFYVDJMTzZqNnJ3dnYwdkNZcEhQNmh5L0tRTVNQaEcyY3lwRmMKdHl6S1Z5NXczUnNodWJRR0pCeGt3M0lsNnYybTAxZ3c4Z3ZFTlJOUVhScXVJTVZuUFMyU3NGU3pnVVBJbFlSQwpibW9WZE5ZcFVuSngyNnF0OFNhek1xeUNEZGVzWGJqbzFqQ3dWVTJwVlpIS2xvOThZNitscEN4TDZxdz0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "temporal-wieisdetrol-cert"
data:
  client.cert: |
    -----BEGIN CERTIFICATE-----
    MIIF0TCCA7mgAwIBAgIUBSVNnaNEJmlizEWuURahO4EEL7swDQYJKoZIhvcNAQEL
    BQAwZjELMAkGA1UEBhMCTkwxCzAJBgNVBAgMAk5IMQswCQYDVQQKDAJESTE9MDsG
    A1UEAww0Y2EtaW50ZXJtZWRpYXRlLWNsaWVudC50ZW1wb3JhbC1jbHVzdGVyLmRp
    Z2luZnJhLm5ldDAeFw0yNTExMDMxMzA0MDVaFw0zMDExMDIxMzA0MDVaMHwxCzAJ
    BgNVBAYTAk5MMRYwFAYDVQQIDA1Ob29yZC1Ib2xsYW5kMRIwEAYDVQQHDAlBbXN0
    ZXJkYW0xGDAWBgNVBAoMD0tOQVcgSHVDIERJIFRDSTEnMCUGA1UEAwweYmFja3Vw
    LndpZWlzZGV0cm9sLmh1Yy5rbmF3Lm5sMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
    MIICCgKCAgEAu3DaSzUYZDMScMg9sHBpG6XPsLZZYXHD7eY5RhHglQZJnI7cO2yP
    8+9Rrh+ptCSLDC8jK+yub4TPEpki/youTuS2FsT6BdhluUhPva1YWWmCmgpF8tNS
    9Nj5+JFhWTWBRFNUK8FilzHmxmRv7gu8yOcLRSvSJOelMfUqh9/S2QHUOL4w6/Q0
    jnNQuOESvQtbHS9MCsxFehH++XT3aM9u5RRhe0++JQqlUK/bpIVsuKFE0a2VT1zO
    8MRCSEGtVnalLDyk66UieGc9rcWX0/fxlZ+x5drATn9q0hUU0HCyspzhmZ7po+aK
    x+NYucv/8PmmR2Iy8MMlYjkHNVVIldu9ne473QI3t2e+NQoMYlpZyt9haDtrcUnx
    5rcDzrbFNlo7B5WpBuBsk1f1hg5Dwfbkn3eH+Fo1TLVz44rmonCfOxQACHCBfIzT
    MnDkl/z/kH5RhdawUjZNxRC8Ss55z5ayG7GXYm6niE/Gv6HytyZkzqn2BJOnN9uB
    LJBM/Rp3erV7LNYRyVo0XNtDz7ctBBfUXwTNqnaUvs6rI4aIHuzefCMtHkfXSlJB
    b2CMtnE3lDJc2pgjzrtBjZ05IDCicEQMTT4/oPfWajZy8CH4MyZVUS07t2LQWeyR
    3CMCFmc0YFUBbW3vQw2ZvnBYMTBq2eDQn7pmBkDmEQr6jakBO4Zzo2ECAwEAAaNh
    MF8wHQYDVR0RBBYwFIISYmFja3VwLmh1Yy5rbmF3Lm5sMB0GA1UdDgQWBBR8+zd8
    0g5SpKlJOo0flIXvfks8GjAfBgNVHSMEGDAWgBQ6ysnUKj4W260vVHtFeWpr5j91
    ajANBgkqhkiG9w0BAQsFAAOCAgEAOwRx9gmFo02DmDAZxK7cEPKMPMaOZOOzZUK5
    3walbUOk7SVGsHXoZqVH1tGsVzsdYmHuME8o3wATdPI7/97zjSvU+BU/MWjdeEnf
    XliiE+TNdcE+iEePLxC3PY3Ipr16b8iy3ICtMyW7CGK2ZLpWCfk+mw1FSwnjSfPE
    IXk0Quf0wDVQPm4H8cARSUsgf7mqz/dWQgwG7UH/GFBce9xT47TRDfhzJDSJMZvM
    Pi5CEobNkgM3Xeug6wtqEloMvHeBg5MFzSSNYagfk7X+Udz4yre+rrxu6vPYT9da
    OPM+0ndbZ8wmwcs76qAdHhfWRIP1Bnqk0bk/LNVmDxThrYiGLNzpYIybePuAJhJd
    iSVfFpzh7QkVbX+xn+dFjCZ8lb7SuxY25gi/t3NGldBUh23eaTvvjUoZfyLq6ZH5
    qYvv7ZqHuBuVM418RxSrYPv6XTzz/iQSp7MM+d09BQ1phZTzuZkeDAve5b7ODP1j
    /I2iNBeEHRK2rjAjsca/Iyaq0neg1VzTd3s1cuxf1gNieq1wbHe/uafY5gYLcJbA
    KvpvZSCDriXPXE1vZ4i5pguPU54RRu2GpDxCZPYPMJVnOrKcIhZyKiXaLvnT9DmS
    gJh7c39QSl+oYVSfG+u9A0lN90I43Vy0b4me6hYhQXlWJ8l9zXSe8gSrqEZZiFyO
    2xMNwIo=
    -----END CERTIFICATE-----

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "temporal-ca-wfm-cert"
data:
  ca.cert: |
    -----BEGIN CERTIFICATE-----
    MIIFrjCCA5agAwIBAgIUY4VsB1hSB4s3aIQw9MmqLgdG1+kwDQYJKoZIhvcNAQEL
    BQAwVzELMAkGA1UEBhMCTkwxCzAJBgNVBAgMAk5IMQswCQYDVQQKDAJESTEuMCwG
    A1UEAwwlcm9vdC1jYS50ZW1wb3JhbC1jbHVzdGVyLmRpZ2luZnJhLm5ldDAeFw0y
    NTAyMTMxMzAxNTRaFw0yNzAyMTMxMzAxNTRaMGYxCzAJBgNVBAYTAk5MMQswCQYD
    VQQIDAJOSDELMAkGA1UECgwCREkxPTA7BgNVBAMMNGNhLWludGVybWVkaWF0ZS1j
    bGllbnQudGVtcG9yYWwtY2x1c3Rlci5kaWdpbmZyYS5uZXQwggIiMA0GCSqGSIb3
    DQEBAQUAA4ICDwAwggIKAoICAQDLbxJ5ojMenxNZNG82eza3AOButzgZ5+qJ2AIZ
    en5+ZjBz5H3zIdFH2nIsfZZMZn7xp073uUR0pCLuBGCnoYmTXH1P4+ReYzOi6F2d
    kJarrzImKip5Z9yE0kq9/x3MRdhmpwq8His3khCmhidhUcr7wfO+FKwUGMgNyTve
    GgQnTCrpB1iDU1dr9ygkPqHmE7EOO/amCOKF+mAF50XYgyZAB9Co/Vn4IpoaHra7
    q7C5D+K6C4PTfyMtHZnDzXwKdu2wxccJYZD5kLXqZMLT2qXZFodPFbAr7BmOyRHm
    GlYkdwveU5UFiot+o3dLurC1XvurJdbo9adD/9Pf0EyuoAsZK3IP0WthZiscsCsS
    DxKk1YSYFFTOudKCO4wYH5pvfmXvw/kufikJxYnudCCnG+1wpG69yDn4gPduNi4Y
    V8qJq1MqRjeI+VwmCStwR56MKAI3iUl/0aF0vTXL3zUbfgGJL10E5PI0u2MbvCS4
    yCXfewZQJ83GYoo4ew2gQ3OSILblNFV8brVoTNJZgg6WVGs4KnZDk8UU+zfvQbNP
    79wCZ6ZKsw+DZmQtjjaDhRMH6AaMk/w2uTe+pC17Xv6qU3YO3qiRagicR9IGTvk8
    U/Bypekvm8QV5NV2mFJIkVFUEvCfU7i1rmgRbvmsYa/iWDh8wPYfOlz+wu32wLTK
    LX49iwIDAQABo2MwYTAdBgNVHQ4EFgQUOsrJ1Co+FtutL1R7RXlqa+Y/dWowHwYD
    VR0jBBgwFoAUp6oM5ljJjfFhLDGu2jcvkMNb8MQwEgYDVR0TAQH/BAgwBgEB/wIB
    ADALBgNVHQ8EBAMCAaYwDQYJKoZIhvcNAQELBQADggIBAIRogiWqp5OsQzvYhjUl
    nD+sTZOqHZkA2HnnIK99ydAza7JzmimQrW6xcf+EGlzgLePW5Y59SCcX5OuSGzTj
    3W5Ap0JHCgkshgT4v97+uvTRCUV5Vhb4ISM0QrQE5R2VCatdoLATFicvwrFP1AAn
    nCbgd/zPY5TWkyG0qK1N0zyYmcXkIrzUTyWaWwsMNS9VjcrEmy4neqRxBsIOq5wp
    08la6u9BqBUoSOBH1sP2OdbBqP8WMxLaK0jWRGxJGHtko1PlJbnxboKACGMFS315
    HdOoKPPmoDuWI0QI0SkvwZsRpHNsuSGSUEN5ZyqkwJTnqb4mCuB8ba6ZHn5SIoWO
    sYkmqv95xWvTJEfuJQH6hoIf1YNsK1oCxmlu3uq5T/ZB6sLm+VGk6+nTwF7eAd9E
    tG8qrcYBQEGveJW5S8M2NHhB1exsM5zkiHFUexQfttXb5XpyFqAUrdgDHtY172i+
    g3MkX7LmHFbxX2xv7ETl+peabOAKFNJ1893L/Uu5GgZ//cx4H3YJC/gZM5gs8/yw
    6CE2U4di+KBgBJk9UROgNs8mmOwQpO4OGvZR+qyzz3tDG0ieiDtuBw8bOsDOn/Ms
    uZZl+21BVqJVa1vTrcI6uy5O30NIzYhVGLTly2R3boC6QtT9qrLECE4/2pzAuyOc
    YElIlc/5qQSzD0Spti5Nl+wj
    -----END CERTIFICATE-----
